### ISSUE TITLE
Overview - As a client, I can make a purchase/return

### ISSUE THREAD

**Issue by patrickspensieri** [patrickspensieri/ConUShop#100]
- [x] #103 Update the SRS
- [x] #104 design the `shopping cart`, `order`, `orderCatalog` and any other necessary components in the SAD (accountable @pbgnz) 
- [x] #105 create database tables and triggers (accountable @Smoudii)
- [x] implement all classes and logic, respecting the design in SAD (accountable @mazennahle)
