### ISSUE TITLE
Software Requirements Specification

### ISSUE THREAD

**Issue by taj-ch** [patrickspensieri/ConUShop#14]
This is the overview of the the SRS documents. Bullets will be completed throughout the project 

NOTE: BEFORE YOU START A TASK: Please make sure that you view the grading scheme so that you understand HOW he will grade our work! he clearly says what he wants for every part of our work...
He expects concurrent properties to be written in temporal logic statements!
He expects extended finite state machines!
He expects operation contracts for all system sequence diagrams!
IT IS VERY CLEAR! ( By now everyone should have understood how the marking scheme works and i will 100% not tolerate any work that does not follow it!) Every time you start something. look at the scheme and check if it applies to your task)
[marking-scheme-2.pdf](https://github.com/patrickspensieri/soen343/files/1351233/marking-scheme-2.pdf)

View example SRS document that I shared with you guys!

- [ ] Oversee the document @mazennahle 

- [ ] Introduction #12 @karlogonzales 
    - Purpose
    - Scope
    - Definitions, acronyms and abbreviations
    - References
    - [ ] **REVIEWED BY :** @rajee10 
- [ ] Overall Description #13 @tusmanakhter @pbgnz 
    - Product perspective
    - Product functions
    - User characteristics
    - Constraints
    - Assumptions and dependencies
    - [ ] **REVIEWED BY :** @patrickspensieri 
- [ ] Specific Requirements #34 @Smoudii 
    - External Interfaces
    - Functional requirements @rajee10 
    - Actor goal list @andypham29 
    - Non-functional requirements @CodeTaj 
    - [ ] **REVIEWED BY :** @Smoudii @tusmanakhter 
    - [ ] **REVIEWED BY :** @pbgnz please review the Non-functional requirements
- [ ] Analysis Models #35 @iamlax @patrickspensieri 
    - [ ] **REVIEWED BY :** @CodeTaj
