### ISSUE TITLE
Software Architecture Document

### ISSUE THREAD

**Issue by taj-ch** [patrickspensieri/ConUShop#16]
Read lecture note 1.1 slide 29
Understand how the hierarchy of UML diagrams works.. note 1.1 slide 21
- [ ] oversee the document @mazennahle
- [x] Introduction #11 @mazennahle
    - [x] **REVIEWED BY :** @tusmanakhter 
- [x] Architectural Representation #22 @Smoudii 
    - [ ] **REVIEWED BY :** @patrickspensieri 
- [x] Architectural Requirements : Goals and constrains @patrickspensieri 
     - Functional Requirements (Use case View)
     - Non-functional requirements
    - [ ] **REVIEWED BY :** @andypham29 
- [X] Use case view (Scenarios) #36 @pbgnz 
    - [ ] **REVIEWED BY :** @iamlax @mazennahle
- [ ] Logical view #36 @tusmanakhter @iamlax 
     - Layers, tiers etc
     - Subsystems
     - Use case realizations
    - [ ] **REVIEWED BY :** @CodeTaj @pbgnz 
- [ ] Development (Implementation) view #36 @pbgnz 
     - Reuse of components and frameworks
    - [ ] **REVIEWED BY :** @patrickspensieri 
- [x] Process view #36 @CodeTaj 
    - [x] **REVIEWED BY :** @tusmanakhter 
- [ ] Deployment (Physical) View #36 @andypham29 @karlogonzales
    - [x] **REVIEWED BY :** @tusmanakhter 
- [ ] Data View ( optional ) - This will be discussed #36
    - [ ] **REVIEWED BY :** 
- [ ] Size and performance @karlogonzales 
    - [ ] **REVIEWED BY :** @rajee10 
- [ ] Quality @rajee10 
    - [ ] **REVIEWED BY :** @Smoudii
