### ISSUE TITLE
Create the Database for our application

### ISSUE THREAD

**Issue by mazennahle** [patrickspensieri/ConUShop#3]
A database holds records of electronics sold by a company as well as records of registered clients and administrators. Electronics can be television sets or computer systems. Televi- sions can be categorized into high-definition, (HD) LED, Smart or 3D. Computer systems can be desktops (display units are sold separately), laptops, or tablets.

- [x] A record for a television contains the detailed dimensions (in centimeters), the weight, the model number (alphanumerical, unique), the brand name and the price. #4

- [x] A record for a desktop computer contains the detailed dimensions (in centimeters), processor type, the RAM size, the weight, the number of CPU cores, the hard drive size, the brand name, the model number (alphanumerical, unique), and the price. #6 

- [x] A record for a monitor display contains the size (in inches), the weight, the the brand name, the model number (alphanumerical, unique), and the price. #8 

- [x] A record for a laptop contains the display size (in inches), the processor type, the RAM size, the weight, the number of CPU cores, the hard drive size, battery information, the brand name, the model number (alphanumerical, unique), the built-in operating system, and the price. Laptops may additionally contain a camera. A laptop may also be of a touch-screen type. #9 

- [x] A record for a tablet computer contains the display size (in inches), the detailed di- mensions (in centimeters), the weight, the processor type, the RAM size, the number of CPU cores, the hard drive size, battery information, the brand name, the model number (alphanumerical, unique), the built-in operating system, camera information, and the price. #7

- [x] A client record consists of a first and last name, a physical and email address, and a phone number. An administrator is a client to the database with privileges. All administrators and clients have a unique id. #17
